# Generated by Django 3.0.4 on 2020-03-30 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_base64', '0002_samplebase64filemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='samplebase64filemodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_base64.SampleParentModel'),
        ),
        migrations.AddField(
            model_name='samplebase64imagemodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_base64.SampleParentModel'),
        ),
    ]
