# Generated by Django 3.0.5 on 2020-04-15 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_history_set',
        ),
        migrations.AddField(
            model_name='user',
            name='chat_users',
            field=models.ManyToManyField(blank=True, related_name='_user_chat_users_+', through='members.UserChatHistory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userchathistory',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user1_chat_history_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userchathistory',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2_chat_history_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userchathistory',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_user1_user2'),
        ),
    ]
