# Generated by Django 3.0.5 on 2020-04-16 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200415_1053'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userchathistory',
            name='unique_user1_user2',
        ),
        migrations.RemoveField(
            model_name='userchathistory',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='userchathistory',
            name='user2',
        ),
        migrations.AddField(
            model_name='userchathistory',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_history_set_by_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchathistory',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_history_set_by_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_users',
            field=models.ManyToManyField(blank=True, through='members.UserChatHistory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userchathistory',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_users'),
        ),
    ]
