version: '3'

services:
  redis:
    image: redis:alpine
    # expose: 컨테이너 간 포트 공유
    expose:
      - '6379'

  nginx:
    image: nginx:latest
    volumes:
      - .config/production.nginx:/etc/nginx/conf.d/default.conf
    # ports: 컨테이너 간 + 호스트와 포트 공유
    ports:
      - '8080:80'

  django:
    build:
      context: .
      dockerfile: .config/Dockerfile.django
    expose:
      - '8000'
    command: gunicorn -c .config/gunicorn.py config.wsgi

  channels:
    build:
      context: .
      dockerfile: .config/Dockerfile.django
    expose:
      - '8001'
    environment:
      - REDIS_HOST=redis
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
